### ISSUE TITLE
[suggestion] Bindings for Nuklear GUI

### ISSUE THREAD

**Issue by olueiro** [stetre/moonlibs#2]
Hello,
Great job!
It would be nice if there were also bindings for the [Nuklear](https://github.com/vurtun/nuklear) GUI

Thank You!

**Comment by stetre** [comment]
Hi, thank you!
As I wrote in response to issue #1 , I'm not going to write other bindings in the near future.
However nuklear is definitely an interesting library, so I may consider it, if I find the time.
Can't promise anything, though.

**Comment by stetre** [comment]
Added [MoonNuklear](https://github.com/stetre/moonnuklear).

**Comment by olueiro** [comment]
Amazing!
Thanks for making this library so fast

I will use it in my works! :-)
Thank you
