### ISSUE TITLE
LuaJIT support

### ISSUE THREAD

**Issue by jordan4ibanez** [stetre/moonlibs#7]
I was wondering if there are any plans to add support to LuaJIT for this project. Thank you.

**Comment by stetre** [comment]
Hi. I'm sorry but no, there aren't any.

**Comment by jordan4ibanez** [comment]
Ah. Well no need to apologize, after all it is your project with your goals. Thank you for responding.

**Comment by stetre** [comment]
Don't mention it. While I understand why people are interested in LuaJIT, in a sense LuaJIT and libraries like these are alternatives. Or at least they are alternative approaches in the aim for speed and extensibility: language implementation and ffi versus C and C bindings. Considering that Lua and LuaJIT diverged a few years ago, I don't feel that supporting the latter is worth the (increased) effort.
