### ISSUE TITLE
Update to Lua 5.4

### ISSUE THREAD

**Issue by EmperorPenguin18** [stetre/moonlibs#9]
I'm not sure if 5.4 has any useful features for this project, but the reason I would like it is so these libraries work with other Lua libraries that have updated.

I know it says in the README >= 5.3 but I get this error when using 5.4: `undefined symbol: lua_newuserdata` which I believe is because moonvulkan is using liblua 5.4 and newuserdata doesn't exist in that.

**Comment by stetre** [comment]
I don't use new features from Lua >= 5.3, but usability with newer versions is definitely an aim. I myself use 5.4 regularly.

As for lua_newuserdata, in 5.4 it is actually defined as a macro for backward compatibility (in lua.h), so the error you get seems strange to me. Are you using a customized version of Lua?

**Comment by EmperorPenguin18** [comment]
Compiling with LUAVER=5.4 fixed the problem. Closing this issue.
